<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class Landing_seeder extends Seeder
{
	public function run()
	{
		$time = new Time();

		$karyawan = [
			[
				'code' => 'IM',
				'nama' => 'Aceng',
				'phone' => 6281224711312,
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'code' => 'GBKSIMP',
				'nama' => 'Novandi',
				'phone' => 6281212609423,
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'code' => 'GBKM3',
				'nama' => 'Zaim',
				'phone' => 6285773465849,
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'code' => 'GBKUBM',
				'nama' => 'Zaim',
				'phone' => 6285776237423,
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'code' => 'GBKJKT',
				'nama' => 'Herdis',
				'phone' => 6281213468456,
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'code' => 'GBKSOLO',
				'nama' => 'Eko',
				'phone' => 6281296211718,
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
		];

		$categories = [
			[
				'category' => 'Pakaian Anak',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'category' => 'Daster',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'category' => 'Gamis',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'category' => 'Kerudung',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'category' => 'Mukena',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'category' => 'Kaos Distro',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
		];

		$sumbers = [
			[
				'sumber' => 'Web GBK Order',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'sumber' => 'Facebook',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'sumber' => 'Instagram',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
		];

		$type_customers = [
			[
				'type' => 'Agen',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'type' => 'Reseller',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
		];

		$customers = [
			'sumbers_id' => 1,
			'type_customers_id' => 2,
			'nama' => 'Aceng Gebeka',
			'phone' => 6282111230484,
			'address' => 'Cikarang',
			'created_at' => $time->toDateTimeString(),
			'updated_at' => $time->toDateTimeString(),
		];

		$orders = [
			'karyawan_id' => 1,
			'customers_id' => 1,
			'total' => 350000,
			'note' => 'Saya mau pesan 2 kang',
			'created_at' => $time->toDateTimeString(),
			'updated_at' => $time->toDateTimeString(),
		];

		$packages = [
			[
				'image_packages' => 'psa.jpg',
				'package' => 'Paket Sample Anak',
				'harga' => 350000,
				'berat' => 4,
				'stock' => 5,
				'categories_id' => 1,
				'rekomend' => 1,
				'keterangan' => 'Dalam paket ini berisi pakaian untuk usia 1-8 tahun dan paket ini cocok sekali untuk anda yang pemula mau mencoba bisnis baju.',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'image_packages' => 'pma.jpg',
				'package' => 'Paket Mini Anak',
				'harga' => 1500000,
				'berat' => 15,
				'stock' => 10,
				'categories_id' => 1,
				'rekomend' => 0,
				'keterangan' => 'Dalam paket ini berisi pakaian untuk anak usia Bayi-10 thn. Paket ini sangat kami rekomendasikan bagi yang sudah punya toko online.',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'image_packages' => 'pua.jpg',
				'package' => 'Paket Usaha Anak',
				'harga' => 3500000,
				'berat' => 30,
				'stock' => 8,
				'categories_id' => 1,
				'rekomend' => 0,
				'keterangan' => 'FREE BANNER bisnis baju murah. Dalam paket ini berisi pakaian untuk anak usia bayi-16 thn. Paket ini sangat kami rekomendasikan bagi yang sudah punya toko online.',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
		];

		$products = [
			// PSA
			[
				'product' => 'Celana anak ompol',
				'slug' => 'celana-anak-ompol',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'celana-anak-ompol.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana cb',
				'slug' => 'celana-cb',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'celana-cb.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana katun anak',
				'slug' => 'celana-katun-anak',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'celana-katun-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Dress putih',
				'slug' => 'dress-putih',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 2,
				'image_product' => 'dress-putih.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Dress sifon anak',
				'slug' => 'dress-sifon-anak',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'dress-sifon-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos belang m',
				'slug' => 'kaos-belang-m',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'kaos-belang-m.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos Belang S',
				'slug' => 'kaos-belang-s',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'kaos-belang-s.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos Java',
				'slug' => 'kaos-java',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'kaos-java.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos kartun',
				'slug' => 'kaos-kartun',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'kaos-kartun.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos raglan',
				'slug' => 'kaos-raglan',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'kaos-raglan.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'krah s',
				'slug' => 'kaos-s',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'kaos-s.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Lekbong',
				'slug' => 'lekbong',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'lekbong.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Lekbong Kartun',
				'slug' => 'lekbong-kartun',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 3,
				'image_product' => 'lekbong-kartun.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set Bola',
				'slug' => 'set-bola',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 2,
				'image_product' => 'set-bola.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set cewe s',
				'slug' => 'set-cewe-s',
				'categories_id' => 1,
				'packages_id' => 1,
				'qtypackages' => 2,
				'image_product' => 'set-cewe-s.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			//PMA
			[
				'product' => 'Celana anak ompol',
				'slug' => 'celana-anak-ompol',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'celana-anak-ompol.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana boxer anak',
				'slug' => 'celana-boxer-anak',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 4,
				'image_product' => 'celana-boxer-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana cb',
				'slug' => 'celana-cb',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 5,
				'image_product' => 'celana-cb.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana kanvas',
				'slug' => 'celana-kanvas',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'celana-kanvas.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana kartun anak',
				'slug' => 'celana-kartun-anak',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 5,
				'image_product' => 'celana-kartun-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana petro',
				'slug' => 'celana-petro',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'celana-petro.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana street anak',
				'slug' => 'celana-street-anak',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 5,
				'image_product' => 'celana-street-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Dress putih',
				'slug' => 'dress-putih',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'dress-putih.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Dress sifon anak',
				'slug' => 'dress-sifon-anak',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'dress-sifon-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'joger loreng s-m',
				'slug' => 'joger-loreng-s-m',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'joger-loreng-s-m.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos belang m',
				'slug' => 'kaos-belang-m',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'kaos-belang-m.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos belang s',
				'slug' => 'kaos-belang-s',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'kaos-belang-s.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos boy junior',
				'slug' => 'kaos-boy-junior',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'kaos-boy-junior.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos fila',
				'slug' => 'kaos-fila',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'kaos-fila.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos java',
				'slug' => 'kaos-java',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 5,
				'image_product' => 'kaos-java.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos karakter',
				'slug' => 'kaos-karakter',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 5,
				'image_product' => 'kaos-karakter.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos kartun',
				'slug' => 'kaos-kartun',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'kaos-kartun.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos lelang branded',
				'slug' => 'kaos-lelang-branded',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'kaos-lelang-branded.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos raglan anak',
				'slug' => 'kaos-raglan-anak',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'kaos-raglan-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos stabilo putih',
				'slug' => 'kaos-stabilo-putih',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'kaos-stabilo-putih.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos stabilo warna',
				'slug' => 'kaos-stabilo-warna',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'kaos-stabilo-warna.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kemeja boy junior',
				'slug' => 'kemeja-boy-junior',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'kemeja-boy-junior.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Krah M',
				'slug' => 'krah-m',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'krah-m.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Lekbong',
				'slug' => 'lekbong',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'lekbong.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Lekbong kartun',
				'slug' => 'lekbong-kartun',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'lekbong-kartun.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set bola',
				'slug' => 'set-bola',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 6,
				'image_product' => 'set-bola.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set cowo s',
				'slug' => 'set-cowo-s',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'set-cowo-s.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set putih anak',
				'slug' => 'set-putih-anak',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'set-putih-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set tp m',
				'slug' => 'set-tp-m',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'set-tp-m.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set vin singlet',
				'slug' => 'set-vin-singlet',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'set-vin-singlet.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos ombak',
				'slug' => 'kaos-ombak',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'kaos-ombak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Tunik raisa',
				'slug' => 'tunik-raisa',
				'categories_id' => 1,
				'packages_id' => 2,
				'qtypackages' => 3,
				'image_product' => 'tunik-raisa.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			// PUA
			[
				'product' => 'Blouse lelang',
				'slug' => 'blouse-lelang',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'blouse-lelang.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Blouse midi',
				'slug' => 'blouse midi',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 5,
				'image_product' => 'blouse midi.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana anak ompol',
				'slug' => 'celana-anak-ompol',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'celana-anak-ompol.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana biggi',
				'slug' => 'celana-biggi',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'celana-biggi.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana boxer anak',
				'slug' => 'celana-boxer-anak',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 5,
				'image_product' => 'celana-boxer-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana cb',
				'slug' => 'celana-cb',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 5,
				'image_product' => 'celana-cb.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana kanvas',
				'slug' => 'celana-kanvas',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 4,
				'image_product' => 'celana-kanvas.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana santai',
				'slug' => 'celana-santai',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'celana-santai.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana petro',
				'slug' => 'celana-petro',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 5,
				'image_product' => 'celana-petro.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana streat stabilo',
				'slug' => 'celana-streat-stabilo',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'celana-streat-stabilo.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana street motif',
				'slug' => 'celana-street-motif',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'celana-street-motif.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Celana stretch bordir',
				'slug' => 'celana-stretch-bordir',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 5,
				'image_product' => 'celana-stretch-bordir.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Dress dena 4-8',
				'slug' => 'dress-dena',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'dress-dena.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Dress sifon anak',
				'slug' => 'dress-sifon-anak',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'dress-sifon-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Jeans nick xl',
				'slug' => 'jeans-nick-xl',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'jeans-nick-xl.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Joger loreng s-m',
				'slug' => 'joger-loreng',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 5,
				'image_product' => 'joger-loreng.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos belang l',
				'slug' => 'kaos-belang',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'kaos-belang.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos belang m',
				'slug' => 'kaos-belang',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'kaos-belang.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos belang xl',
				'slug' => 'kaos-belang',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'kaos-belang.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'kaos fila',
				'slug' => 'kaos-fila',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-fila.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos java',
				'slug' => 'kaos-java',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 10,
				'image_product' => 'kaos-java.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos karakter',
				'slug' => 'kaos-karakter',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-karakter.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos kartun',
				'slug' => 'kaos-kartun',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'kaos-kartun.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos lelang branded',
				'slug' => 'kaos-lelang-branded',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-lelang-branded.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos minerva',
				'slug' => 'kaos-minerva',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-minerva.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos nanokids',
				'slug' => 'kaos-nanokids',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-nanokids.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos ombak',
				'slug' => 'kaos-ombak',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-ombak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos raglan anak',
				'slug' => 'kaos-raglan-anak',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'kaos-raglan-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos stabilo putih',
				'slug' => 'kaos-stabilo-putih',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-stabilo-putih.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'kaos stabilo warna',
				'slug' => 'kaos-stabilo-warna',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'kaos-stabilo-warna.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kaos stabilo warna tp',
				'slug' => 'kaos-stabilo-warna-tp',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'kaos-stabilo-warna-tp.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Kemeja boy junior',
				'slug' => 'kemeja-boy-junior',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 5,
				'image_product' => 'kemeja-boy-junior.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Krah l',
				'slug' => 'krah',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'krah.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Krah s',
				'slug' => 'krah',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'krah.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'lekbong',
				'slug' => 'lekbong',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'lekbong.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Lekbong kartun',
				'slug' => 'lekbong-kartun',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 12,
				'image_product' => 'lekbong-kartun.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set bola',
				'slug' => 'set-bola',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'set-bola.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set cewe l',
				'slug' => 'set-cewe',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'set-cewe.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set cowo l',
				'slug' => 'set-cowo',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'set-cowo.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set jos boy',
				'slug' => 'set-jos-boy',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'set-jos-boy.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'set kodok',
				'slug' => 'set-kodok',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'set-kodok.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'set pro 4-8',
				'slug' => 'set-pro',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'set-pro.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set putih anak',
				'slug' => 'set-putih-anak',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'set-putih-anak.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set singlet putih',
				'slug' => 'set-singlet-putih',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'set-singlet-putih.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'set tp l',
				'slug' => 'set-tp',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'set-tp.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'set tp s',
				'slug' => 'set-tp',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 6,
				'image_product' => 'set-tp.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
			[
				'product' => 'Set vinluis m',
				'slug' => 'set-vinluis',
				'categories_id' => 1,
				'packages_id' => 3,
				'qtypackages' => 3,
				'image_product' => 'set-vinluis.jpg',
				'created_at' => $time->toDateTimeString(),
				'updated_at' => $time->toDateTimeString(),
			],
		];

		$detail_orders = [
			'orders_id' => 1,
			'packages_id' => 1,
			'qty' => 1,
			'subtotal' => 350000,
			'created_at' => $time->toDateTimeString(),
			'updated_at' => $time->toDateTimeString(),
		];

		$this->db->table('karyawan')->insertBatch($karyawan);
		$this->db->table('categories')->insertBatch($categories);
		$this->db->table('sumbers')->insertBatch($sumbers);
		$this->db->table('type_customers')->insertBatch($type_customers);
		$this->db->table('customers')->insert($customers);
		$this->db->table('orders')->insert($orders);
		$this->db->table('packages')->insertBatch($packages);
		$this->db->table('products')->insertBatch($products);
		$this->db->table('detail_orders')->insert($detail_orders);
	}
}
